### ISSUE TITLE
update hexagon support

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/ClangBuiltLinux.github.io#26]
we should refresh the homepage to denote better support for hexagon

**Comment by nickdesaulniers** [comment]
should update kernel docs, too.

**Comment by nathanchance** [comment]
I forgot to link this to https://github.com/ClangBuiltLinux/ClangBuiltLinux.github.io/commit/99601c7d23233232523db4646dcd4322675d697b.
